### PR TITLE
Add https://cantstop.fun to notable projects

### PR DESCRIPTION
**Pull request by simlmx**
Adding [cantstop.fun][1] to the notable projects list.

I wasn't exactly sure where to put it in the list: I followed the almost alphabetical order.
I'm happy to create a following PR sorting everything in alphabetical order if you folks think it's a good idea.

#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [x] Test coverage is 100% (or you have a story for why it's ok).

[1]: https://cantstop.fun

### CODE REVIEW

**Review by delucis — APPROVED** [review]

**Comment by delucis** [comment]
Thanks @simlmx! There hasn’t been any strict order, but PRs are always welcome :-)

**Comment by simlmx** [comment]
Cool!

While I'm at it what do you think of switching the game page and the code urls? I think people expect to get to the game when they click on the game's name. So items of the list could look like

- [Can't Stop!](https://cantstop.fun) [[code](https://github.com/simlmx/cantstop)] - The classic "push your luck" dice game.

**Comment by delucis** [comment]
Why not? There are a few variations and not each project is a game, so maybe the name could just be bolded and then there could be three categories of link: play / code / tutorial, e.g.:

- **Can't Stop!** - [play]() / [code]() - The classic "push your luck" dice game.

Thanks for this!

**Comment by simlmx** [comment]
Good point! I'll try something out today or tomorrow and we can always iterate on the PR!

You're welcome and thanks to you too!

**Pull request merged**
