### PR TITLE
Sort and uniformize the notable games

### PR DESCRIPTION
**Pull request by simlmx**
Sort and uniformize the list of projects using boardgame.io

* Sort games in alphabetical order
* Make each list item uniform
* Make the first paragraph marginally more concise
* Add github stars to open source projects, to highlight popular
  projects
* Reorganize the markdown code

Result:
boardgame_io_notable_projects_md_at_simlmx_sort-notable-projects_·_simlmx_boardgame_io

#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [x] Test coverage is 100% (or you have a story for why it's ok).

### CODE REVIEW

**Comment by flamecoals** [comment]
When we started this list, we tried to order it by some proxy metric of popularity --- i.e. github stars. Some projects are harder to know, but I like this more than alphabetical

**Comment by simlmx** [comment]
I see! The thing is that most of those projects have < 20 stars, and some are not open source, which I guess is why we had this pseudo-alphabetical order. Also stars will change over time, especially for new projects, which would be painful to maintain.

Something we could easily do is add a number of github stars widget next to the projects, if you want to highlight more popular github projects.

Let me know what you think!

**Comment by simlmx** [comment]
I did try a few things out for fun, here's a version with the github stars:
boardgame_io_notable_projects_md_at_simlmx_sort-notable-projects-2_·_simlmx_boardgame_io

**Comment by flamecoals** [comment]
That's great addition!

**Comment by delucis** [comment]
Badges look nice @simlmx!

**Comment by simlmx** [comment]
I updated the PR! Let me know what you think.

**Review by delucis — APPROVED** [review]
Thanks for taking the time to do this @simlmx! These look great.

I added a couple of small tweaks so it works well when rendered on the docs site:

image

**Pull request merged**
