### PR TITLE
fix(master): Don’t crash on missing chatMessage

### PR DESCRIPTION
**Pull request by nopeless**
This line was throwing unhandled promise rejections when I was testing invalid packets

#### Checklist

- [ this was edited in github] Use a separate branch in your local repo (not `main`).
- [no ] Test coverage is 100% (or you have a story for why it's ok)

### CODE REVIEW

**Review by delucis — COMMENTED** [review]
Looks like there are some linter errors. Try running `npm run prettier` to fix those.

**Comment by nopeless** [comment]
@delucis yeah I figured it out, thanks. I was thinking about this the other night about having a schema validation like validate.js. But then I realized this chat packet is something different from the other events (for example it is not handled by redux). So I guess this simple fix will suffice

**Comment by nopeless** [comment]
wait, let me fix a few other stuff

**Review by delucis — CHANGES_REQUESTED** [review]
Ah, right. You’re using the optional chaining syntax `?.` but our setup doesn’t support that yet, so tests are still throwing errors.

Rather than adding this check to `isAuthentic`, how about we just add some simple validation at the start of the `onChatMessage` method? Something like

```js
if (!chatMessage) {
  return { error: 'missing chatMessage' };
}
```

(I think that’s enough, because the authentication method should account for an undefined or null player ID.)

**Comment by nopeless** [comment]
Actually while fixing some other stuff, I realized that the other stuff should be a separate PR. I pinged you on gitter.

**Review by delucis — APPROVED** [review]
Thanks @nopeless!

**Pull request merged**
